name: Tag version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current tag version
        id: get_current_tag
        run: |
          if [ $(git tag -l "v*") ]; then
            echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"
          else
            echo "::set-output name=tag::v0.0.0"
          fi

      - name: Create new tag
        id: create_tag
        run: |
          NEW_TAG=$(echo ${{ steps.get_current_tag.outputs.tag }} | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Push new tag to repository
        run: |
          git push origin ${{ env.NEW_TAG }}
        env:
          NEW_TAG: ${{ env.NEW_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
