name: Update data version tag

on:
  push:
    branches:
      - main
    paths:
      - configuration/**
      - modules/**

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create an incremental release
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: false
          prev_tag: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
